# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171112_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='foolowing',
            field=models.ManyToManyField(related_name='_user_foolowing_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
