# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171113_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-specified', 'Not Sepcified')], max_length=80, null=True),
        ),
    ]
