# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171113_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foolowing',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
