# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20171113_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='like',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='like',
            name='image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
